// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pomelo.EntityFrameworkCore.MySql.Storage.Internal;
using sistema_gestor_de_tiquetes_aereos.Src.Shared.Context;

#nullable disable

namespace sistema_gestor_de_tiquetes_aereos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418172500_CreateBaggage")]
    partial class CreateBaggage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("sistema_gestor_de_tiquetes_aereos.Src.Modules.Baggage.Infrastructure.Entity.BaggageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("BaggageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("baggage_type_id");

                    b.Property<decimal>("ChargedPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("charged_price")
                        .HasPrecision(18, 2)
                        .HasDefaultValue(0m);

                    b.Property<int>("CheckinId")
                        .HasColumnType("int")
                        .HasColumnName("checkin_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight_kg")
                        .HasPrecision(5, 2);

                    b.HasKey("Id").HasName("PK_baggage");

                    b.HasIndex("BaggageTypeId").HasName("IX_baggage_baggage_type_id");

                    b.HasIndex("CheckinId").HasName("IX_baggage_checkin_id");

                    b.ToTable("baggage", (string)null).HasAnnotation("MySql:CharSet", "utf8mb4");
                });
#pragma warning restore 612, 618
        }
    }
}
